name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: matejak/argbash:latest

    steps:
    - uses: actions/checkout@v3

    - name: Use argbash to generate script
      run: make argbash
